import { Room, Equipment, Booking, AcademicBlock, UserSession, Feedback } from './types';

export const INITIAL_ROOMS: Room[] = [
  {
    id: 'room-aud-rahman',
    code: 'MY-1201',
    name: 'Auditorium Ar-Rahman',
    building: 'Menara YARSI',
    floor: 12,
    capacity: 700,
    type: 'auditorium',
    requiresYayasanApproval: true,
    facilities: [
      'Panggung Megah',
      'Videotron LED Screen 8x4m',
      'Sound System Line Array',
      '8 Mic Wireless',
      'VIP Green Room & Lounge',
      'Ruang Operator Audio Visual',
      'AC Central 50 PK',
      'Live Streaming Setup',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=1200&q=80',
    description: 'Auditorium utama Universitas YARSI dengan kapasitas 700 kursi teater. Cocok untuk wisuda, seminar internasional, kuliah umum akbar, dan perayaan universitas.',
    isActive: true,
    locationDetails: 'Lantai 12 Menara YARSI, Akses Lift Utama / VIP',
    picName: 'Pak Hendra (LPF Menara)',
    picPhone: '0812-3456-7890',
  },
  {
    id: 'room-aud-razi',
    code: 'FK-0201',
    name: 'Auditorium Ar-Razi',
    building: 'Gedung FK & FKG (Gedung B)',
    floor: 2,
    capacity: 350,
    type: 'auditorium',
    requiresYayasanApproval: true,
    facilities: [
      'Tiered Theater Seating (350 kursi)',
      'Dual Laser Projector 6500 ANSI',
      'Sound System Dolby 7.1',
      '4 Mic Wireless & Podium',
      'Hybrid Zoom Room System',
      'AC Central',
      'Foyer Registrasi Luas',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?auto=format&fit=crop&w=1200&q=80',
    description: 'Auditorium bergaya amfiteater bertingkat dengan akustik prima, ideal untuk simposium medis, kuliah perdana, dan lokakarya akademik.',
    isActive: true,
    locationDetails: 'Lantai 2 Gedung Fakultas Kedokteran (Gedung B)',
    picName: 'Ibu Rahmawati (LPF Gedung B)',
    picPhone: '0813-8877-6655',
  },
  {
    id: 'room-senat-8',
    code: 'MY-0801',
    name: 'Ruang Rapat Senat Universitas',
    building: 'Menara YARSI',
    floor: 8,
    capacity: 45,
    type: 'meeting',
    requiresYayasanApproval: true,
    facilities: [
      'Meja Bundar Eksekutif Senat',
      'Polycom Video Conference 4K',
      '45 Unit Microphone Delegate',
      'Smart Interactive Board 85"',
      'Ruang Jamuan VIP Terpisah',
      'Pantry Khusus',
      'High-Speed Dedicated WiFi',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1517502884422-41eaead166d4?auto=format&fit=crop&w=1200&q=80',
    description: 'Ruang rapat prestisius untuk Sidang Senat Universitas, Rapat Pimpinan Eksekutif, dan Pertemuan Dewan Pembina/Pengurus Yayasan.',
    isActive: true,
    locationDetails: 'Lantai 8 Menara YARSI, Area Rektorat',
    picName: 'Sekretariat Rektorat',
    picPhone: '0811-9988-7744',
  },
  {
    id: 'room-smart-301',
    code: 'GC-0301',
    name: 'Smart Classroom 301',
    building: 'Gedung C (FTI / FEB / FH)',
    floor: 3,
    capacity: 50,
    type: 'classroom',
    requiresYayasanApproval: false,
    facilities: [
      'Interactive Smart Display 75"',
      'Hybrid PTZ Auto-Tracking Camera',
      'Microphone Array Ceiling',
      'Kursi Ergonomis Roda Fleksibel',
      'Dual AC Split 2 PK',
      'Power Outlet per Meja Mahasiswa',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=1200&q=80',
    description: 'Ruang kelas modern berbasis teknologi interaktif dan hybrid learning, mendukung diskusi kelompok dinamis.',
    isActive: true,
    locationDetails: 'Lantai 3 Gedung C, Sayap Kiri',
    picName: 'Staf LPF Gedung C',
    picPhone: '0857-1234-5678',
  },
  {
    id: 'room-smart-302',
    code: 'GC-0302',
    name: 'Smart Classroom 302',
    building: 'Gedung C (FTI / FEB / FH)',
    floor: 3,
    capacity: 50,
    type: 'classroom',
    requiresYayasanApproval: false,
    facilities: [
      'Interactive Smart Display 75"',
      'Hybrid PTZ Camera',
      'Ceiling Mic',
      'Kursi Fleksibel',
      'Dual AC Split 2 PK',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?auto=format&fit=crop&w=1200&q=80',
    description: 'Ruang kuliah pintar berkapasitas 50 mahasiswa dengan fasilitas kolaborasi digital lengkap.',
    isActive: true,
    locationDetails: 'Lantai 3 Gedung C, Sayap Kanan',
    picName: 'Staf LPF Gedung C',
    picPhone: '0857-1234-5678',
  },
  {
    id: 'room-lab-ai',
    code: 'GC-0504',
    name: 'Laboratorium AI & Data Science',
    building: 'Gedung C (FTI / FEB / FH)',
    floor: 5,
    capacity: 40,
    type: 'lab',
    requiresYayasanApproval: false,
    facilities: [
      '40 Unit PC RTX 4080 GPU',
      'Gigabit Ethernet LAN & Server Node',
      'Dual Projector 4K',
      'Sound Bar & Wireless Mic',
      'Air Conditioner 3 PK',
      'UPS Backup Power System',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=1200&q=80',
    description: 'Lab komputasi performa tinggi untuk workshop Artificial Intelligence, Data Science, Hackathon, dan Praktikum Informatika.',
    isActive: true,
    locationDetails: 'Lantai 5 Gedung C, Laboratorium Komputer FTI',
    picName: 'Laboran FTI (Mas Bayu)',
    picPhone: '0812-9876-5432',
  },
  {
    id: 'room-collab-4',
    code: 'MY-0402',
    name: 'Ruang Diskusi & Collaboration Hub',
    building: 'Menara YARSI',
    floor: 4,
    capacity: 35,
    type: 'meeting',
    requiresYayasanApproval: false,
    facilities: [
      'Modular Bean Bags & Sofa Diskusi',
      'Full Wall Whiteboard Magnetic',
      'Smart TV 65" Wireless Casting',
      'Coffee & Tea Dispenser Station',
      'High Speed WiFi 6',
      'AC Split 2 PK',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1200&q=80',
    description: 'Ruang kreatif santai untuk brainstorming ormawa, mentoring dosen-mahasiswa, dan rapat komite kegiatan kampus.',
    isActive: true,
    locationDetails: 'Lantai 4 Menara YARSI, Area Co-Working Mahasiswa',
    picName: 'Kemahasiswaan YARSI',
    picPhone: '0819-0123-4567',
  },
  {
    id: 'room-studio-pod',
    code: 'MY-0305',
    name: 'Studio Podcasting & Multimedia',
    building: 'Menara YARSI',
    floor: 3,
    capacity: 10,
    type: 'studio',
    requiresYayasanApproval: false,
    facilities: [
      'Ruang Kedap Suara Akustik Pro',
      '4 Unit Mic Shure SM7B + Boom Arm',
      'Audio Mixer Rodecaster Pro II',
      '3 Unit Kamera Sony Cinema FX3 4K',
      'Studio Lighting RGB Panel',
      'Teleprompter 17"',
      'AC Ultra Silent',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&w=1200&q=80',
    description: 'Studio rekaman broadcast profesional untuk podcast universitas, pembuatan video pembelajaran daring MOOC, dan wawancara ilmiah.',
    isActive: true,
    locationDetails: 'Lantai 3 Menara YARSI, Media Center',
    picName: 'Tim Humas & Media YARSI',
    picPhone: '0812-1122-3344',
  },
  {
    id: 'room-aula-fkg',
    code: 'FK-0401',
    name: 'Aula Mini FKG & Dental Center',
    building: 'Gedung FK & FKG (Gedung B)',
    floor: 4,
    capacity: 120,
    type: 'hall',
    requiresYayasanApproval: false,
    facilities: [
      '120 Kursi Banquet Lipat',
      'Sound System JBL 2000W',
      'Laser Projector Full HD',
      '2 Mic Wireless Handheld + 1 Clip-On',
      'Podium Pembicara',
      'AC Central',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=1200&q=80',
    description: 'Aula serbaguna ukuran sedang untuk seminar keperawatan/kedokteran gigi, rapat yudisium, dan temu alumni.',
    isActive: true,
    locationDetails: 'Lantai 4 Gedung FKG',
    picName: 'Staf Administrasi FKG',
    picPhone: '0813-2233-4455',
  },
];

export const AVAILABLE_EQUIPMENTS: Equipment[] = [
  {
    id: 'eq-proj-laser',
    name: 'Proyektor Laser High-Lumen (4K / 6500 ANSI)',
    category: 'audio_visual',
    icon: 'Projector',
    isSpecialRequest: false,
  },
  {
    id: 'eq-sound-mic',
    name: 'Sound System + 4 Mic Wireless & Stand',
    category: 'audio_visual',
    icon: 'Mic',
    isSpecialRequest: false,
  },
  {
    id: 'eq-zoom-kit',
    name: 'Hybrid Zoom Kit (PTZ Tracking Camera + Ceiling Mic)',
    category: 'audio_visual',
    icon: 'Video',
    isSpecialRequest: false,
  },
  {
    id: 'eq-chairs-extra',
    name: 'Kursi Lipat Tambahan (Paket 50 Unit)',
    category: 'furniture',
    icon: 'Armchair',
    isSpecialRequest: false,
  },
  {
    id: 'eq-podium-vip',
    name: 'Podium Kayu Jati VIP & Standing Banner Logo YARSI',
    category: 'furniture',
    icon: 'Tv',
    isSpecialRequest: false,
  },
  {
    id: 'eq-ac-standing',
    name: 'Standing AC Ekstra 5 PK (2 Unit)',
    category: 'hvac',
    icon: 'Wind',
    isSpecialRequest: true,
  },
  {
    id: 'eq-catering-perm',
    name: 'Izin Konsumsi / Area Buffet Catering Koridor',
    category: 'service',
    icon: 'Utensils',
    isSpecialRequest: true,
  },
  {
    id: 'eq-it-support',
    name: 'Pendampingan Teknisi IT & Audio Visual Standby',
    category: 'service',
    icon: 'Headset',
    isSpecialRequest: false,
  },
];

export const INITIAL_BOOKINGS: Booking[] = [
  {
    id: 'bk-001',
    bookingCode: 'YARSI-BK-2026-0042',
    roomId: 'room-aud-rahman',
    roomName: 'Auditorium Ar-Rahman',
    building: 'Menara YARSI',
    floor: 12,
    userId: 'user-mhs-1',
    userName: 'Ahmad Fikri Pratama',
    userEmail: 'ahmad.fikri@mhs.yarsi.ac.id',
    userNimNidn: '1402022001',
    userRole: 'mahasiswa',
    userPhone: '081298765432',
    userOrganization: 'BEM Fakultas Teknologi Informasi',
    department: 'Teknik Informatika',
    title: 'YARSI Tech Festival 2026: AI Innovation Summit & Exhibition',
    category: 'seminar',
    description: 'Seminar Nasional dan Pameran Proyek AI Mahasiswa menghadirkan narasumber dari BRIN dan Google Developer Expert.',
    estimatedAttendees: 550,
    date: '2026-08-16',
    startTime: '08:00',
    endTime: '16:00',
    status: 'RECOMMENDED_YAYASAN',
    requiresYayasanApproval: true,
    equipments: [
      { equipmentId: 'eq-proj-laser', equipmentName: 'Proyektor Laser High-Lumen', quantity: 1 },
      { equipmentId: 'eq-sound-mic', equipmentName: 'Sound System + 4 Mic Wireless', quantity: 2 },
      { equipmentId: 'eq-zoom-kit', equipmentName: 'Hybrid Zoom Kit', quantity: 1 },
      { equipmentId: 'eq-it-support', equipmentName: 'Pendampingan Teknisi IT', quantity: 1 },
    ],
    documentUrl: '#',
    documentName: 'Proposal_YARSI_TechFest_2026_BEM_FTI.pdf',
    lpfNotes: 'Fasilitas dan kesiapan teknisi LPF diverifikasi aman. Diteruskan ke Yayasan untuk izin auditorium.',
    lpfApprovedAt: '2026-08-14 10:15',
    lpfApprovedBy: 'Bambang Sudibyo (Staf LPF)',
    qrCodeToken: 'QR-YARSI-BK-0042-SECURE-8821',
    createdAt: '2026-08-13 14:20',
  },
  {
    id: 'bk-002',
    bookingCode: 'YARSI-BK-2026-0043',
    roomId: 'room-aud-razi',
    roomName: 'Auditorium Ar-Razi',
    building: 'Gedung FK & FKG (Gedung B)',
    floor: 2,
    userId: 'user-dsn-1',
    userName: 'Dr. dr. Siti Nurhaliza, Sp.A',
    userEmail: 'siti.nurhaliza@yarsi.ac.id',
    userNimNidn: '0314058201',
    userRole: 'dosen',
    userPhone: '081122334455',
    userOrganization: 'Fakultas Kedokteran',
    department: 'Ilmu Kesehatan Anak',
    title: 'Simposium Nasional Kedokteran Islam & Etika Medis Kontemporer',
    category: 'seminar',
    description: 'Simposium ilmiah kedokteran bekerja sama dengan RS YARSI untuk dokter muda dan spesialis.',
    estimatedAttendees: 280,
    date: '2026-08-17',
    startTime: '08:30',
    endTime: '15:00',
    status: 'APPROVED',
    requiresYayasanApproval: true,
    equipments: [
      { equipmentId: 'eq-proj-laser', equipmentName: 'Proyektor Laser High-Lumen', quantity: 1 },
      { equipmentId: 'eq-sound-mic', equipmentName: 'Sound System + 4 Mic Wireless', quantity: 1 },
      { equipmentId: 'eq-catering-perm', equipmentName: 'Izin Konsumsi Foyer', quantity: 1 },
    ],
    documentUrl: '#',
    documentName: 'Surat_Tugas_Simposium_FK_2026.pdf',
    lpfNotes: 'Disetujui LPF.',
    lpfApprovedAt: '2026-08-12 09:00',
    lpfApprovedBy: 'Bambang Sudibyo (LPF)',
    yayasanNotes: 'Disetujui Sekretariat Yayasan YARSI. Harap jaga kebersihan ruang.',
    yayasanApprovedAt: '2026-08-13 11:30',
    yayasanApprovedBy: 'Drs. H. M. Shadiq (Yayasan YARSI)',
    qrCodeToken: 'QR-YARSI-BK-0043-VERIFIED-9912',
    createdAt: '2026-08-11 10:00',
  },
  {
    id: 'bk-003',
    bookingCode: 'YARSI-BK-2026-0044',
    roomId: 'room-lab-ai',
    roomName: 'Laboratorium AI & Data Science',
    building: 'Gedung C (FTI / FEB / FH)',
    floor: 5,
    userId: 'user-mhs-1',
    userName: 'Ahmad Fikri Pratama',
    userEmail: 'ahmad.fikri@mhs.yarsi.ac.id',
    userNimNidn: '1402022001',
    userRole: 'mahasiswa',
    userPhone: '081298765432',
    userOrganization: 'Himpunan Mahasiswa Informatika (HIMATIF)',
    department: 'Teknik Informatika',
    title: 'Bootcamp Hands-on: Building LLM Agents with Python',
    category: 'workshop',
    description: 'Pelatihan pemrograman praktis untuk anggota HIMATIF dengan materi dasar Generative AI dan API integration.',
    estimatedAttendees: 38,
    date: '2026-08-15',
    startTime: '09:00',
    endTime: '12:30',
    status: 'PENDING_LPF',
    requiresYayasanApproval: false,
    equipments: [
      { equipmentId: 'eq-it-support', equipmentName: 'Pendampingan Teknisi IT', quantity: 1 },
    ],
    documentUrl: '#',
    documentName: 'Permohonan_Pinjam_Lab_HIMATIF.pdf',
    qrCodeToken: 'QR-YARSI-BK-0044-PENDING-4431',
    createdAt: '2026-08-14 09:30',
  },
  {
    id: 'bk-004',
    bookingCode: 'YARSI-BK-2026-0040',
    roomId: 'room-smart-301',
    roomName: 'Smart Classroom 301',
    building: 'Gedung C (FTI / FEB / FH)',
    floor: 3,
    userId: 'user-dsn-2',
    userName: 'Fathurrahman, S.Kom., M.T.',
    userEmail: 'fathur@yarsi.ac.id',
    userNimNidn: '0319089002',
    userRole: 'dosen',
    userPhone: '081399887766',
    userOrganization: 'Program Studi Informatika',
    department: 'Fakultas Teknologi Informasi',
    title: 'Kuliah Tamu Industri: Microservices Architecture in Fintech',
    category: 'kuliah',
    description: 'Kuliah tamu mata kuliah Rekayasa Perangkat Lunak Lanjut.',
    estimatedAttendees: 45,
    date: '2026-08-13',
    startTime: '13:00',
    endTime: '15:30',
    status: 'COMPLETED',
    requiresYayasanApproval: false,
    equipments: [
      { equipmentId: 'eq-zoom-kit', equipmentName: 'Hybrid Zoom Kit', quantity: 1 },
    ],
    qrCodeToken: 'QR-YARSI-BK-0040-DONE-1234',
    createdAt: '2026-08-08 14:00',
    feedbackSubmitted: true,
  },
  {
    id: 'bk-005',
    bookingCode: 'YARSI-BK-2026-0039',
    roomId: 'room-collab-4',
    roomName: 'Ruang Diskusi & Collaboration Hub',
    building: 'Menara YARSI',
    floor: 4,
    userId: 'user-mhs-1',
    userName: 'Ahmad Fikri Pratama',
    userEmail: 'ahmad.fikri@mhs.yarsi.ac.id',
    userNimNidn: '1402022001',
    userRole: 'mahasiswa',
    userPhone: '081298765432',
    userOrganization: 'BEM FTI YARSI',
    department: 'Teknik Informatika',
    title: 'Rapat Pleno Koordinasi Program Kerja BEM 2026',
    category: 'rapat',
    description: 'Penyelarasan target KPI dan jadwal open recruitment kepanitiaan.',
    estimatedAttendees: 25,
    date: '2026-08-12',
    startTime: '16:00',
    endTime: '18:00',
    status: 'COMPLETED',
    requiresYayasanApproval: false,
    equipments: [],
    qrCodeToken: 'QR-YARSI-BK-0039-DONE-8899',
    createdAt: '2026-08-10 11:00',
    feedbackSubmitted: false, // User can submit feedback for this!
  },
  {
    id: 'bk-006',
    bookingCode: 'YARSI-BK-2026-0045',
    roomId: 'room-studio-pod',
    roomName: 'Studio Podcasting & Multimedia',
    building: 'Menara YARSI',
    floor: 3,
    userId: 'user-dsn-1',
    userName: 'Dr. dr. Siti Nurhaliza, Sp.A',
    userEmail: 'siti.nurhaliza@yarsi.ac.id',
    userNimNidn: '0314058201',
    userRole: 'dosen',
    userPhone: '081122334455',
    userOrganization: 'Humas & PMB YARSI',
    department: 'Fakultas Kedokteran',
    title: 'Podcast "YARSI Sehat": Mengenal Deteksi Dini Tumbuh Kembang Anak',
    category: 'kemahasiswaan',
    description: 'Episode 14 Podcast resmi Kampus YARSI untuk kanal YouTube & Spotify.',
    estimatedAttendees: 4,
    date: '2026-08-15',
    startTime: '13:30',
    endTime: '15:30',
    status: 'APPROVED',
    requiresYayasanApproval: false,
    equipments: [
      { equipmentId: 'eq-it-support', equipmentName: 'Teknisi Multimedia', quantity: 1 },
    ],
    qrCodeToken: 'QR-YARSI-BK-0045-OK-7722',
    createdAt: '2026-08-13 16:00',
  }
];

export const INITIAL_ACADEMIC_BLOCKS: AcademicBlock[] = [
  {
    id: 'acad-01',
    title: 'Algoritma & Struktur Data (Kelas A & B)',
    courseCode: 'IF2104',
    lecturerName: 'Dr. Eng. Irfan Hakim, S.T., M.Kom.',
    roomId: 'room-smart-301',
    roomName: 'Smart Classroom 301',
    building: 'Gedung C (FTI / FEB / FH)',
    dayOfWeek: 1, // Senin
    startTime: '08:00',
    endTime: '10:30',
    semester: 'Semester Ganjil 2026/2027',
    faculty: 'Teknologi Informasi',
    studentGroup: 'IF-2024-A',
    isActive: true,
  },
  {
    id: 'acad-02',
    title: 'Basis Data Terdistribusi (Praktikum)',
    courseCode: 'IF3208',
    lecturerName: 'Fathurrahman, S.Kom., M.T.',
    roomId: 'room-lab-ai',
    roomName: 'Laboratorium AI & Data Science',
    building: 'Gedung C (FTI / FEB / FH)',
    dayOfWeek: 1, // Senin
    startTime: '13:00',
    endTime: '15:30',
    semester: 'Semester Ganjil 2026/2027',
    faculty: 'Teknologi Informasi',
    studentGroup: 'IF-2023-B',
    isActive: true,
  },
  {
    id: 'acad-03',
    title: 'Anatomi Klinis & Fisiologi Dasar (Modul 1.2)',
    courseCode: 'KD1102',
    lecturerName: 'Prof. Dr. dr. H. Fachruddin, Sp.OT(K)',
    roomId: 'room-aud-razi',
    roomName: 'Auditorium Ar-Razi',
    building: 'Gedung FK & FKG (Gedung B)',
    dayOfWeek: 2, // Selasa
    startTime: '08:00',
    endTime: '11:45',
    semester: 'Semester Ganjil 2026/2027',
    faculty: 'Kedokteran',
    studentGroup: 'FK-2025-Angkatan',
    isActive: true,
  },
  {
    id: 'acad-04',
    title: 'Hukum Kesehatan & Bioetika Islam',
    courseCode: 'HK4109',
    lecturerName: 'Dr. Hj. Mardiana, S.H., M.H.',
    roomId: 'room-smart-302',
    roomName: 'Smart Classroom 302',
    building: 'Gedung C (FTI / FEB / FH)',
    dayOfWeek: 3, // Rabu
    startTime: '10:00',
    endTime: '12:30',
    semester: 'Semester Ganjil 2026/2027',
    faculty: 'Hukum & Kedokteran',
    studentGroup: 'FH-2023-C',
    isActive: true,
  },
  {
    id: 'acad-05',
    title: 'Manajemen Keuangan Syariah',
    courseCode: 'EB3101',
    lecturerName: 'Dr. Muhammad Rizal, S.E., M.Si.',
    roomId: 'room-smart-301',
    roomName: 'Smart Classroom 301',
    building: 'Gedung C (FTI / FEB / FH)',
    dayOfWeek: 4, // Kamis
    startTime: '13:30',
    endTime: '16:00',
    semester: 'Semester Ganjil 2026/2027',
    faculty: 'Ekonomi & Bisnis',
    studentGroup: 'FEB-2024-A',
    isActive: true,
  },
];

export const INITIAL_FEEDBACKS: Feedback[] = [
  {
    id: 'fb-001',
    bookingId: 'bk-004',
    bookingCode: 'YARSI-BK-2026-0040',
    roomId: 'room-smart-301',
    roomName: 'Smart Classroom 301',
    userId: 'user-dsn-2',
    userName: 'Fathurrahman, S.Kom., M.T.',
    cleanlinessRating: 5,
    facilityRating: 5,
    staffPunctualityRating: 5,
    overallRating: 5,
    notes: 'Ruangan sangat bersih, smart display berfungsi sempurna untuk kuliah tamu hybrid, dan tim LPF sangat sigap.',
    createdAt: '2026-08-13 16:30',
  },
];

export const DEMO_USERS: UserSession[] = [
  {
    id: 'user-mhs-1',
    name: 'Ahmad Fikri Pratama',
    identifier: '1402022001',
    role: 'mahasiswa',
    email: 'ahmad.fikri@mhs.yarsi.ac.id',
    department: 'Teknik Informatika (FTI)',
    organization: 'BEM FTI YARSI (Ketua)',
    phone: '081298765432',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
  },
  {
    id: 'user-dsn-1',
    name: 'Dr. dr. Siti Nurhaliza, Sp.A',
    identifier: '0314058201',
    role: 'dosen',
    email: 'siti.nurhaliza@yarsi.ac.id',
    department: 'Fakultas Kedokteran',
    organization: 'Departemen Ilmu Kesehatan Anak',
    phone: '081122334455',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&q=80',
  },
  {
    id: 'user-lpf-1',
    name: 'Bambang Sudibyo, S.T.',
    identifier: 'LPF-0912',
    role: 'admin_lpf',
    email: 'lpf@yarsi.ac.id',
    department: 'Biro Layanan Pengelolaan Fasilitas & Umum',
    organization: 'Universitas YARSI',
    phone: '0812-8899-0011',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
  },
  {
    id: 'user-yayasan-1',
    name: 'Drs. H. Muhammad Shadiq, M.M.',
    identifier: 'YYS-004',
    role: 'admin_yayasan',
    email: 'sekretariat.yayasan@yarsi.ac.id',
    department: 'Biro Sekretariat & Aset Yayasan',
    organization: 'Yayasan YARSI',
    phone: '0811-3322-1100',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
  },
];
