export enum Role {
  USER = 'USER',
  ADMIN = 'ADMIN',
  SUPERADMIN = 'SUPERADMIN',
}

export enum BookingStatus {
  PENDING = 'PENDING',
  VERIFIED = 'VERIFIED',
  RECOMMENDED = 'RECOMMENDED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  RETURNED = 'RETURNED',
  CANCELED = 'CANCELED',
  EXPIRED = 'EXPIRED',
}

export enum ActivityType {
  SEMINAR = 'SEMINAR',
  WORKSHOP = 'WORKSHOP',
  PELATIHAN = 'PELATIHAN',
  RAPAT = 'RAPAT',
  KUNJUNGAN = 'KUNJUNGAN',
  KULIAH_TAMU = 'KULIAH_TAMU',
  KULIAH = 'KULIAH',
  AKREDITASI = 'AKREDITASI',
  UJIAN_CBT = 'UJIAN_CBT',
  LAINNYA = 'LAINNYA',
}

