export enum Role {
  GUEST = 'GUEST',
  USER = 'USER',
  ADMIN_UNIV = 'ADMIN_UNIV',
  ADMIN_YAYASAN = 'ADMIN_YAYASAN',
  ADMIN_UMUM = 'ADMIN_UMUM',
  ADMIN_LPF = 'ADMIN_LPF',
  YAYASAN = 'YAYASAN',
  SUPERADMIN = 'SUPERADMIN',
}

export enum BookingStatus {
  PENDING = 'PENDING',
  VERIFIED = 'VERIFIED',
  RECOMMENDED = 'RECOMMENDED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  RETURNED = 'RETURNED',
  CANCELED = 'CANCELED',
}

export enum ActivityType {
  SEMINAR = 'SEMINAR',
  WORKSHOP = 'WORKSHOP',
  PELATIHAN = 'PELATIHAN',
  RAPAT = 'RAPAT',
  KUNJUNGAN = 'KUNJUNGAN',
  KULIAH_TAMU = 'KULIAH_TAMU',
  KULIAH = 'KULIAH',
  AKREDITASI = 'AKREDITASI',
  UJIAN_CBT = 'UJIAN_CBT',
  LAINNYA = 'LAINNYA',
}

